# config.yaml
max_cpus: 16
ilp_prob_threshold: 0.75  # Adjusted for novelty detection
hhsearch_novel_threshold: 60  # Adjusted for novelty detection
blast_novel_threshold: 25  # Adjusted for novelty detection
use_deepneuropepred: true
cleavage_threshold: 0.5
colabfold_model_type: "alphafold2_multimer_v3"
colabfold_num_recycle: 3
mafft_options: "--globalpair --maxiterate 1000"
phylo_tool: "iqtree"  # Options: "iqtree", "phyloformer"
clade_methods: ["ete", "autophy", "treecluster"]
foldtree_filter_plddt: 40
ml_feature_selection: 10
ml_cross_validation_folds: 5
pymol_path: "/path/to/pymol"  # Optional, for fallback
ngl_viewer_path: "output/ngl_viewer"  # Path to NGL Viewer files
flask_app_port: 5000  # Port for Flask web app
colabfold_path: "/path/to/colabfold_batch"
interpro_path: "interproscan.sh"
tmalign_refs:
  1TRZ: "references/1TRZ.pdb"
  6RLX: "references/6RLX.pdb"
  bombyxin: "references/bombyxin.pdb"
  dynamic: "preprocess/dynamic_ref.pdb"
deepneuropepred_model: "deepneuropepred/pretrain_model/DeepNeuropePred.pth"
deepneuropepred_script: "deepneuropepred/test.py"
ngl_viewer_path: "output/ngl_viewer"  # Path to NGL Viewer files
